### ISSUE TITLE
Warning:  The 1-th region point lies outside the convex hull.

### ISSUE THREAD

**Issue by NataCalc** [libigl/tetgen#7]
Hello,

While meshing imported STl model using tetrahedral elements using tetGen I get this error:
Warning:  The 1-th region point lies outside the convex hull.
```
Warning:  The 1-th region point lies outside the convex hull.
"/Users/s2986149/Desktop/GIBBON/lib_ext/tetGen/mac64/tetgen" -pq1.2AaY "/Users/s2986149/Desktop/GIBBON/data/temp/tetgenmodel.smesh": Segmentation fault
--- Done --- 08-Feb-2019 14:58:06

```

Many thanks for suggestions.
Cheers,
NataCalc
[tetGen_mesh_sizing_function_Scaphoid_Lunate.m.zip](https://github.com/libigl/tetgen/files/2843808/tetGen_mesh_sizing_function_Scaphoid_Lunate.m.zip)
[Scaphoid_improved_surface.stl.zip](https://github.com/libigl/tetgen/files/2843809/Scaphoid_improved_surface.stl.zip)

**Comment by alecjacobson** [comment]
This is just a mirror of the tetgen code. Not the host repository. Please send bug reports to tetgen directly.
